<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">
  <!ELEMENT mime-type (comment+, (acronym,expanded-acronym)? , (icon? | generic-icon? | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
  <!ATTLIST mime-type type CDATA #REQUIRED>
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>
  <!ELEMENT acronym (#PCDATA)>
  <!ATTLIST acronym xml:lang CDATA #IMPLIED>
  <!ELEMENT expanded-acronym (#PCDATA)>
  <!ATTLIST expanded-acronym xml:lang CDATA #IMPLIED>
  <!ELEMENT icon EMPTY>
  <!ATTLIST icon name CDATA #REQUIRED>
  <!ELEMENT generic-icon EMPTY>
  <!ATTLIST generic-icon name (application-x-executable|audio-x-generic|folder|font-x-generic|image-x-generic|package-x-generic|text-html|text-x-generic|text-x-generic-template|text-x-script|video-x-generic|x-office-address-book|x-office-calendar|x-office-document|x-office-presentation|x-office-spreadsheet) #REQUIRED>
  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>
  <!ATTLIST glob weight CDATA "50">
  <!ATTLIST glob case-sensitive CDATA #IMPLIED>
  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA "50">
  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>
  <!ELEMENT treemagic (treematch)+>
  <!ATTLIST treemagic priority CDATA "50">
  <!ELEMENT treematch (treematch)*>
  <!ATTLIST treematch path CDATA #REQUIRED>
  <!ATTLIST treematch type (file|directory|link) #IMPLIED>
  <!ATTLIST treematch match-case (true|false) #IMPLIED>
  <!ATTLIST treematch executable (true|false) #IMPLIED>
  <!ATTLIST treematch non-empty (true|false) #IMPLIED>
  <!ATTLIST treematch mimetype CDATA #IMPLIED>
  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
  <!ATTLIST root-XML localName CDATA #REQUIRED>
  <!ELEMENT alias EMPTY>
  <!ATTLIST alias type CDATA #REQUIRED>
  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of type CDATA #REQUIRED>
]>

<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">

  <!-- APPLICATION/* -->

  <mime-type type="application/andrew-inset">
    <comment>ATK Inset</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/dicom">
    <comment>DICOM Image</comment>
    <acronym>DICOM</acronym>
    <expanded-acronym>Digital Imaging and Communications in Medicine</expanded-acronym>
    <icon name="application-dicom"/>
    <glob pattern="dicomdir"/>
    <glob pattern="*.dcm"/>
    <magic priority="50">
      <match offset="128" type="string" value="DICM"/>
    </magic>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>Electronic Book Document</comment>
    <acronym>ePub</acronym>
    <expanded-acronym>Electronic Publication</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.epub"/>
    <magic priority="70">
      <match offset="0" type="string" value="PK\003\004">
        <match offset="30" type="string" value="mimetype">
          <match offset="38" type="string" value="application/epub+zip"/>
          <match offset="43" type="string" value="application/epub+zip"/>
        </match>
      </match>
    </magic>
    <sub-class-of type="application/zip"/>
  </mime-type>
  <mime-type type="application/geo+json">
    <alias type="application/vnd.geo+json"/>
    <comment>GeoJSON Geospatial Data</comment>
    <icon name="text-json"/>
    <glob pattern="*.geojson"/>
    <glob pattern="*.geo.json"/>
    <sub-class-of type="application/json"/>
  </mime-type>
  <mime-type type="application/gnunet-directory">
    <comment>GNUnet Search File</comment>
    <magic priority="50">
      <match offset="0" type="string" value="\211GND\r\n\032\n"/>
    </magic>
    <glob pattern="*.gnd"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator Document</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/javascript">
    <comment>JavaScript Program</comment>
    <alias type="application/x-javascript"/>
    <alias type="text/javascript"/>
    <icon name="text-x-javascript"/>
    <glob pattern="*.javascript"/>
    <glob pattern="*.js"/>
    <glob pattern="*.jsm"/>
    <glob pattern="*.mjs"/>
    <magic priority="100">
      <match offset="0" type="string" value="eval &quot;exec /bin/gjs"/>
      <match offset="0" type="string" value="eval &quot;exec /usr/bin/gjs"/>
      <match offset="0" type="string" value="eval &quot;exec /usr/local/bin/gjs"/>
      <match offset="2:16" type="string" value="/bin/env gjs"/>
      <match offset="2:16" type="string" value="/bin/env jsc"/>
      <match offset="2:16" type="string" value="/bin/env node"/>
      <match offset="2:16" type="string" value="/bin/env rhino"/>
      <match offset="2:16" type="string" value="/usr/bin/env gjs"/>
      <match offset="2:16" type="string" value="/usr/bin/env jsc"/>
      <match offset="2:16" type="string" value="/usr/bin/env node"/>
      <match offset="2:16" type="string" value="/usr/bin/env rhino"/>
      <match offset="2:16" type="string" value="/usr/bin/gjs"/>
      <match offset="2:16" type="string" value="/usr/bin/jsc"/>
      <match offset="2:16" type="string" value="/usr/bin/node"/>
      <match offset="2:16" type="string" value="/usr/bin/rhino"/>
      <match offset="2:16" type="string" value="/usr/local/bin/gjs"/>
      <match offset="2:16" type="string" value="/usr/local/bin/jsc"/>
      <match offset="2:16" type="string" value="/usr/local/bin/node"/>
      <match offset="2:16" type="string" value="/usr/local/bin/rhino"/>
    </magic>
    <sub-class-of type="application/ecmascript"/>
  </mime-type>
  <mime-type type="application/jrd+json">
    <comment>JRD Document</comment>
    <acronym>JRD</acronym>
    <expanded-acronym>JSON Resource Descriptor</expanded-acronym>
    <icon name="text-json"/>
    <glob pattern="*.jrd"/>
    <sub-class-of type="application/json"/>
  </mime-type>
  <mime-type type="application/json">
    <comment>JSON Document</comment>
    <acronym>JSON</acronym>
    <expanded-acronym>JavaScript Object Notation</expanded-acronym>
    <icon name="text-json"/>
    <glob pattern="*.json"/>
    <sub-class-of type="application/javascript"/>
  </mime-type>
  <mime-type type="application/json-patch+json">
    <comment>JSON Patch</comment>
    <acronym>JSON</acronym>
    <expanded-acronym>JavaScript Object Notation</expanded-acronym>
    <icon name="text-json"/>
    <glob pattern="*.json-patch"/>
    <sub-class-of type="application/json"/>
  </mime-type>
  <mime-type type="application/ld+json">
    <comment>JSON-LD document</comment>
    <acronym>JSON-LD</acronym>
    <expanded-acronym>JavaScript Object Notation for Linked Data</expanded-acronym>
    <icon name="text-json"/>
    <glob pattern="*.jsonld"/>
    <sub-class-of type="application/json"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded File</comment>
    <icon name="application-mac-binhex40"/>
    <magic priority="50">
      <match offset="11" type="string" value="must be converted with BinHex"/>
    </magic>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment>Mathematica Notebook</comment>
    <alias type="application/x-mathematica"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.nb"/>
    <magic priority="50">
      <match offset="0" type="string" value="(************** Content-type: application/mathematica"/>
      <match offset="100:256" type="string" value="This notebook can be used on any computer system with Mathematica"/>
      <match offset="10:256" type="string" value="This is a Mathematica Notebook file.  It contains ASCII text"/>
    </magic>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/mathml+xml">
    <comment>MathML Document</comment>
    <acronym>MathML</acronym>
    <expanded-acronym>Mathematical Markup Language</expanded-acronym>
    <alias type="text/mathml"/>
    <icon name="text-mathml"/>
    <glob pattern="*.mml"/>
    <root-XML namespaceURI="http://www.w3.org/1998/Math/MathML" localName="math"/>
    <sub-class-of type="application/xml"/>
  </mime-type>
  <mime-type type="application/mbox">
    <comment>Mailbox File</comment>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.mbox"/>
    <magic priority="20">
      <match offset="0" type="string" value="From "/>
    </magic>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/metalink+xml">
    <comment>Metalink File</comment>
    <glob pattern="*.metalink"/>
    <magic priority="50">
      <match offset="0:256" type="string" value="&lt;metalink version=&quot;3.0&quot;"/>
    </magic>
    <root-XML namespaceURI="http://www.metalinker.org/" localName="metalink"/>
    <sub-class-of type="application/xml"/>
  </mime-type>
  <mime-type type="application/metalink4+xml">
    <comment>Metalink File</comment>
    <glob pattern="*.meta4"/>
    <magic priority="50">
      <match offset="0:256" type="string" value="&lt;metalink xmlns=&quot;urn"/>
    </magic>
    <root-XML namespaceURI="urn:ietf:params:xml:ns:metalink" localName="metalink"/>
    <sub-class-of type="application/xml"/>
  </mime-type>
  <mime-type type="application/msword-template">
    <comment>Word template</comment>
    <sub-class-of type="application/msword"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.dot"/>
  </mime-type>
  <mime-type type="application/mxf">
    <comment>MXF Video</comment>
    <acronym>MXF</acronym>
    <expanded-acronym>Material Exchange Format</expanded-acronym>
    <generic-icon name="video-x-generic"/>
    <magic priority="50">
      <match offset="0:256" type="string" value="\x06\x0e\x2b\x34\x02\x05\x01\x01\x0d\x01\x02\x01\x01\x02"/>
    </magic>
    <glob pattern="*.mxf"/>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>Unknown</comment>
    <glob pattern="*.bin"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA Document</comment>
    <acronym>ODA</acronym>
    <expanded-acronym>Office Document Architecture</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/oxps">
    <comment>XPS Document</comment>
    <acronym>XPS</acronym>
    <expanded-acronym>Open XML Paper Specification</expanded-acronym>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.oxps"/>
    <glob pattern="*.xps"/>
    <alias type="application/vnd.ms-xpsdocument"/>
    <alias type="application/xps"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF Document</comment>
    <acronym>PDF</acronym>
    <expanded-acronym>Portable Document Format</expanded-acronym>
    <alias type="application/x-pdf"/>
    <alias type="image/pdf"/>
    <alias type="application/acrobat"/>
    <alias type="application/nappdf"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.pdf"/>
    <magic priority="50">
      <match offset="0:1024" type="string" value="%PDF-"/>
    </magic>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <alias type="application/pgp"/>
    <comment>PGP/MIME-encrypted message header</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match offset="0" type="string" value="-----BEGIN PGP MESSAGE-----"/>
    </magic>
    <glob pattern="*.pgp"/>
    <glob pattern="*.gpg"/>
    <glob pattern="*.asc" weight="10"/>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <acronym>PGP</acronym>
    <expanded-acronym>Pretty Good Privacy</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match offset="0" type="big16" value="0x9500"/>
      <match offset="0" type="big16" value="0x9501"/>
      <match offset="0" type="big16" value="0x9900"/>
      <match offset="0" type="big16" value="0x9901"/>
      <match offset="0" type="string" value="-----BEGIN PGP PRIVATE KEY BLOCK-----"/>
      <match offset="0" type="string" value="-----BEGIN PGP PUBLIC KEY BLOCK-----"/>
    </magic>
    <glob pattern="*.asc" weight="10"/>
    <glob pattern="*.gpg"/>
    <glob pattern="*.key" weight="80"/>
    <glob pattern="*.pgp"/>
    <glob pattern="*.pkr"/>
    <glob pattern="*.skr"/>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>Detached OpenPGP signature</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic priority="50">
      <match offset="0" type="string" value="-----BEGIN PGP SIGNATURE-----"/>
    </magic>
    <glob pattern="*.asc" weight="10"/>
    <glob pattern="*.sig"/>
    <glob pattern="*.pgp"/>
    <glob pattern="*.key" weight="80"/>
    <glob pattern="*.gpg"/>
  </mime-type>
  <mime-type type="application/pkcs10">
    <comment>PKCS#10 Certificate Request</comment>
    <acronym>PKCS#10</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p10"/>
    <glob pattern="*.csr"/>
  </mime-type>
  <mime-type type="application/pkcs10+pem">
    <comment>PKCS#10 Certificate Request (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN CERTIFICATE REQUEST-----" offset="0"/>
      <match type="string" value="-----BEGIN NEW CERTIFICATE REQUEST-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkcs12+pem">
    <comment>PKCS#12 Personal Key and Certificates (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN PKCS12-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>PKCS#7 Message and Certificates</comment>
    <acronym>PKCS#7</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p7b"/>
    <glob pattern="*.p7c"/>
    <glob pattern="*.p7m"/>
    <glob pattern="*.spc"/>
    <alias type="application/x-pkcs7-certificates"/>
  </mime-type>
  <mime-type type="application/pkcs7-mime+pem">
    <comment>PKCS#7 Message and Certificates (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN PKCS7-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>PKCS#7 Signature</comment>
    <acronym>S/MIME</acronym>
    <expanded-acronym>Secure/Multipurpose Internet Mail Extensions</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/pkcs8">
    <comment>PKCS#8 Personal Key</comment>
    <acronym>PKCS#8</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p8" weight="75"/>
    <glob pattern="*.pkcs8"/>
  </mime-type>
  <mime-type type="application/pkcs8-encrypted">
    <comment>PKCS#8 Private Key (Encrypted)</comment>
    <acronym>PKCS</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <glob pattern="*.p8e"/>
  </mime-type>
  <mime-type type="application/pkcs8+pem">
    <comment>PKCS#8 Personal Key (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN PRIVATE KEY-----" offset="0"/>
      <match type="string" value="-----BEGIN ENCRYPTED PRIVATE KEY-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkix-cert">
    <comment>X.509 Certificate</comment>
    <glob pattern="*.cer" weight="75"/>
    <glob pattern="*.crt"/>
    <glob pattern="*.cert"/>
    <alias type="application/x-x509-ca-cert"/>
    <alias type="application/x-x509-user-cert"/>
  </mime-type>
  <mime-type type="application/pkix-cert+pem">
    <comment>X.509 Certificate (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN CERTIFICATE-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/pkix-crl">
    <comment>Certificate Revocation List</comment>
    <acronym>CRL</acronym>
    <expanded-acronym>Certificate Revocation List</expanded-acronym>
    <glob pattern="*.crl" weight="75"/>
  </mime-type>
  <mime-type type="application/pkix-crl+pem">
    <comment>Certificate Revocation List (PEM Format)</comment>
    <sub-class-of type="application/x-pem-file"/>
    <magic priority="75">
      <match type="string" value="-----BEGIN X509 CRL-----" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PS Document</comment>
    <acronym>PS</acronym>
    <expanded-acronym>PostScript</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match offset="0" type="string" value="\004%!"/>
      <match offset="0" type="string" value="%!"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/raml+yaml">
    <comment>RAML Document</comment>
    <acronym>RAML</acronym>
    <expanded-acronym>RESTful API Modeling Language</expanded-acronym>
    <sub-class-of type="application/x-yaml"/>
    <magic>
      <match offset="0" type="string" value="#%RAML "/>
    </magic>
    <glob pattern="*.raml"/>
  </mime-type>
  <mime-type type="application/relax-ng-compact-syntax">
    <comment>RELAX NG XML Schema</comment>
    <acronym>RELAX NG</acronym>
    <expanded-acronym>REgular LAnguage for XML Next Generation</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.rnc"/>
    <alias type="application/x-rnc"/>
  </mime-type>
  <mime-type type="application/rtf">
    <acronym>RTF</acronym>
    <comment>RTF Document</comment>
    <expanded-acronym>Rich Text Format</expanded-acronym>
    <alias type="text/rtf"/>
    <glob pattern="*.rtf"/>
    <icon name="application-rtf"/>
    <magic priority="50">
      <match offset="0" type="string" value="{\\rtf"/>
    </magic>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/smil+xml">
    <comment>SMIL Document</comment>
    <acronym>SMIL</acronym>
    <expanded-acronym>Synchronized Multimedia Integration Language</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <alias type="application/smil"/>
    <generic-icon name="video-x-generic"/>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
    <glob pattern="*.kino"/>
    <magic priority="55">
      <match offset="0:256" type="string" value="&lt;smil"/>
    </magic>
    <root-XML namespaceURI="http://www.w3.org/2001/SMIL20/Language" localName="smil"/>
    <root-XML namespaceURI="http://www.w3.org/2005/SMIL21/Language" localName="smil"/>
    <root-XML namespaceURI="http://www.w3.org/ns/SMIL" localName="smil"/>
  </mime-type>
  <mime-type type="application/xhtml+xml">
    <comment>XHTML Page</comment>
    <acronym>XHTML</acronym>
    <expanded-acronym>Extensible HyperText Markup Language</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-html"/>
    <glob pattern="*.htm"/>
    <glob pattern="*.html"/>
    <glob pattern="*.xht"/>
    <glob pattern="*.xhtml"/>
    <magic priority="60">
      <match offset="0:256" type="string" value="//W3C//DTD XHTML "/>
      <match offset="0:256" type="string" value="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>
      <match offset="0:256" type="string" value="&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml"/>
      <match offset="0:256" type="string" value="&lt;HTML xmlns=&quot;http://www.w3.org/1999/xhtml"/>
    </magic>
    <root-XML namespaceURI="http://www.w3.org/1999/xhtml" localName="html"/>
  </mime-type>
  <mime-type type="application/xml">
    <alias type="text/xml"/>
    <acronym>XML</acronym>
    <comment>XML Document</comment>
    <expanded-acronym>eXtensible Markup Language</expanded-acronym>
    <icon name="text-xml"/>
    <magic priority="40">
      <match offset="0" type="string" value="&lt;?xml"/>
      <match offset="0" type="string" value="&lt;!--"/>
    </magic>
    <glob pattern="*.rng"/>
    <glob pattern="*.xbl"/>
    <glob pattern="*.xml"/>
    <glob pattern="*.xsd"/>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/xml-dtd">
    <acronym>DTD</acronym>
    <alias type="text/x-dtd"/>
    <comment>DTD File</comment>
    <expanded-acronym>Document Type Definition</expanded-acronym>
    <icon name="text-xml"/>
    <glob pattern="*.dtd"/>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/xslt+xml">
    <acronym>XSLT</acronym>
    <comment>XSLT Stylesheet</comment>
    <expanded-acronym>eXtensible Stylesheet Language Transformation</expanded-acronym>
    <icon name="text-xml"/>
    <glob pattern="*.xsl"/>
    <glob pattern="*.xslt"/>
    <sub-class-of type="application/xml"/>
  </mime-type>
  <mime-type type="application/xspf+xml">
    <comment>XSPF Playlist</comment>
    <acronym>XSPF</acronym>
    <expanded-acronym>XML Shareable Playlist Format</expanded-acronym>
    <alias type="application/x-xspf+xml"/>
    <generic-icon name="audio-x-generic"/>
    <glob pattern="*.xspf"/>
    <magic priority="50">
      <match offset="0:64" type="string" value="&lt;playlist version=&quot;1"/>
      <match offset="0:64" type="string" value="&lt;playlist version='1"/>
    </magic>
    <root-XML namespaceURI="http://xspf.org/ns/0/" localName="playlist"/>
    <sub-class-of type="application/xml"/>
  </mime-type>
  <mime-type type="application/zstd">
    <_comment>Zstandard Archive</_comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="60">
      <match type="little32" value="0xFD2FB528" offset="0"/>
    </magic>
    <glob pattern="*.zst"/>
  </mime-type>

  <!-- APPLICATION/prs.* -->

  <mime-type type="application/prs.plucker">
    <comment>Plucker Document</comment>
    <generic-icon name="x-office-document"/>
    <magic priority="80">
      <match offset="60" type="string" value="DataPlkr"/>
    </magic>
  </mime-type>

  <!-- APPLICATION/vnd.* -->

  <mime-type type="application/vnd.android.package-archive">
    <comment>Android Package</comment>
    <icon name="apk"/>
    <sub-class-of type="application/x-java-archive"/>
    <glob pattern="*.apk"/>
  </mime-type>
  <mime-type type="application/vnd.coffeescript">
    <comment>CoffeeScript Document</comment>
    <icon name="application-x-javascript"/>
    <glob pattern="*.coffee" weight="95"/>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/vnd.font-fontforge-sfd">
    <comment>Fontforge Spline Font Database</comment>
    <icon name="application-fontforge-sfd"/>
    <glob pattern="*.sfd"/>
    <magic>
      <match type="string" offset="0" value="SplineFontDB"/>
    </magic>
    <sub-class-of type="text/plain"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 Spreadsheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <magic priority="50">
      <match offset="0" type="string" value="\x00\x00\x02\x00\x06\x04\x06\x00\x08\x00\x00\x00\x00\x00"/>
    </magic>
    <glob pattern="*.123"/>
    <glob pattern="*.wk1"/>
    <glob pattern="*.wk3"/>
    <glob pattern="*.wk4"/>
    <glob pattern="*.wks"/>
    <alias type="application/lotus123"/>
    <alias type="application/wk1"/>
    <alias type="application/x-123"/>
    <alias type="application/x-lotus123"/>
    <alias type="zz-application/zz-winassoc-123"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-wordpro">
    <comment>Lotus Word Pro</comment>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match offset="0" type="string" value="WordPro"/>
    </magic>
    <glob pattern="*.lwp"/>
  </mime-type>
  <mime-type type="application/vnd.ms-access">
    <comment>JET/Access Database</comment>
    <acronym>JET</acronym>
    <expanded-acronym>Joint Engine Technology</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic priority="50">
      <match offset="0" type="string" value="\x00\x01\x00\x00Standard Jet DB"/>
    </magic>
    <glob pattern="*.mdb"/>
    <alias type="application/mdb"/>
    <alias type="application/msaccess"/>
    <alias type="application/vnd.msaccess"/>
    <alias type="application/x-mdb"/>
    <alias type="application/x-msaccess"/>
    <alias type="zz-application/zz-winassoc-mdb"/>
  </mime-type>
  <mime-type type="application/vnd.ms-asf">
    <comment>ASF Video</comment>
    <acronym>ASF</acronym>
    <expanded-acronym>Advanced Streaming Format</expanded-acronym>
    <alias type="video/x-ms-asf"/>
    <alias type="video/x-ms-asf-plugin"/>
    <alias type="video/x-ms-wm"/>
    <glob pattern="*.asf"/>
    <magic priority="50">
      <match offset="0" type="big32" value="0x3026b275"/>
      <match offset="0" type="string" value="[Reference]"/>
    </magic>
  </mime-type>
  <mime-type type="application/vnd.ms-cab-compressed">
    <comment>Microsoft Cabinet Archive</comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="60">
      <match type="string" offset="0" value="MSCF\0\0\0\0"/>
    </magic>
    <glob pattern="*.cab"/>
    <alias type="zz-application/zz-winassoc-cab"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Microsoft Excel Worksheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <magic priority="50">
      <match offset="2080" type="string" value="Microsoft Excel 5.0 Worksheet"/>
    </magic>
    <glob pattern="*.xla"/>
    <glob pattern="*.xlc"/>
    <glob pattern="*.xld"/>
    <glob pattern="*.xll"/>
    <glob pattern="*.xlm"/>
    <glob pattern="*.xls"/>
    <glob pattern="*.xlt"/>
    <glob pattern="*.xlw"/>
    <alias type="application/msexcel"/>
    <alias type="application/x-msexcel"/>
    <alias type="zz-application/zz-winassoc-xls"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.addin.macroEnabled.12">
    <comment>Excel Add-In</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.xlam"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.sheet.binary.macroEnabled.12">
    <comment>Microsoft Excel Worksheet</comment>
    <glob pattern="*.xlsb"/>
    <generic-icon name="x-office-spreadsheet"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.sheet.macroEnabled.12">
    <comment>Microsoft Excel Worksheet</comment>
    <glob pattern="*.xlsm"/>
    <generic-icon name="x-office-spreadsheet"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.template.macroEnabled.12">
    <comment>Microsoft Excel Worksheet Template</comment>
    <glob pattern="*.xltm"/>
    <generic-icon name="x-office-spreadsheet"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.template"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>Microsoft PowerPoint Presentation</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.ppz"/>
    <glob pattern="*.ppt"/>
    <glob pattern="*.pps"/>
    <glob pattern="*.pot"/>
    <alias type="application/mspowerpoint"/>
    <alias type="application/powerpoint"/>
    <alias type="application/x-mspowerpoint"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint.addin.macroEnabled.12">
    <comment>PowerPoint Add-In</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.ppam"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint.slide.macroEnabled.12">
    <comment>PowerPoint Slide</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.sldm"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.presentationml.slide"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint.slideshow.macroEnabled.12">
    <comment>PowerPoint Presentation</comment>
    <generic-icon name="x-office-presentation"/>
    <glob pattern="*.ppsm"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.presentationml.slideshow"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint.presentation.macroEnabled.12">
    <comment>Microsoft PowerPoint Presentation</comment>
    <glob pattern="*.pptm"/>
    <generic-icon name="x-office-presentation"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.presentationml.presentation"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint.template.macroEnabled.12">
    <comment>Microsoft PowerPoint Presentation Template</comment>
    <glob pattern="*.potm"/>
    <generic-icon name="x-office-presentation"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.presentationml.template"/>
  </mime-type>